openapi: 3.0.2
info:
  title: Test
  version: 0.0.1
  description: API definition of test
  contact:
    name: creator's name
    url: http://creator.homepage.address
    email: creator@creator.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
paths:
  /tests:
    summary: Global operations on tests
    get:
      tags:
      - tests
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Test'
              examples:
                tests_json:
                  value:
                  -
                    id: 1
          description: Get list of tests
      operationId: GetTest
      summary: Get list of tests
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Test'
            examples:
              1:
                value:
                  id: 1
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
              examples:
                1:
                  value:
                    id: 1
          description: Changed Test
      operationId: Post Test
      summary: Post Test        
  /tests/{id}:
    summary: Specific operation on tests
    get:
      parameters:
      - examples:
          1:
            value: 1
        name: id
        description: Test name
        schema:
          type: integer
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
              examples:
                1:
                  value:
                    id: 1
          description: tests with specified id
      operationId: GetTestById
      summary: Get Test by id
      description: Get Test by id
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Test'
            examples:
              1:
                value:
                  id: 1
        required: true
      parameters:
      - examples:
          1:
            value: 1
        name: id
        description: Test name
        schema:
          type: integer
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
              examples:
                1:
                  value:
                    id: 1
          description: Changed Test
      operationId: PatchTest
      summary: Patch existing Test
    parameters:
    - name: id
      description: Test id
      schema:
        type: integer
      in: path
      required: true
components:
  schemas:
    Test:
      title: Root Type for Test
      description: The root of the Test type's schema.
      type: object
      properties:
        id:
          description: id of this Test
          type: integer
tags:
  - name: Test
    description: Test resource
